server:
  port: 8888
spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  #JPA Configuration:
  jpa:
      database: MySQL
      show-sql: true
      generate-ddl: true
      hibernate.ddl-auto: update
      hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrate

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.mshd.mapper: debug


wechat:
  appId: wx16ea5811c16c2db2
  appSecret: 2fb1942ceb55c34dd0d47a3ff4529306
  # 商户号
  mchId: 1516918841
  # 商品描述
  body: test测试1
  # 商户key
  key: Blbbianliba11223344Blbbianliba12
  p12Pass: 1516918841