server:
  port: 8001
spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.mshd.mapper: debug