spring:
  datasource:
    druid:
      min-idle: 100
      url: jdbc:mysql://weilaifu.mysql.rds.aliyuncs.com:3306/treat?zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: demo_test
      password: 11223344
      max-active: 1000
  redis:
    host: 101.201.144.134
    port: 3104
    lettuce:
      pool:
        min-idle: 100
    database: 13
    password: 730947a71392472ba65a68a09fd00b8c
aliyun:
  oss:
    AccessKeyID: LTAIPxACpM1voKll
    AccessKeySecret: 85vjeEKlf4bZvlcvHi1XSumy39tfz6
    endpoint: oss-cn-beijing.aliyuncs.com
    sonAccessKeyID: LTAIHgdiUYGPuRsG
    sonAccessKeySecret: 2pgaiHc9TKwcUKwrxt0N2LSy3ZS4qn
    roleArn: acs:ram::1861742825276971:role/aliyunosstokengeneratorrole
swagger2:
  enable: true


