spring:
  datasource:
    druid:
      min-idle: 100
      url: jdbc:mysql://weilaifu.mysql.rds.aliyuncs.com:3306/treat?zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: demo_test
      password: 11223344
      max-active: 1000
  redis:
    host: 101.201.144.134
    password: 730947a71392472ba65a68a09fd00b8c
    port: 3104
    lettuce:
      pool:
        min-idle: 100
    database: 1

server:
  port: 8001

swagger2:
  enable: true