spring:
  datasource:
    druid:
      min-idle: 100
      url: jdbc:mysql://localhost:3306/free?zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
      max-active: 1000
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 100
    database: 0
    password:
aliyun:
  oss:
    AccessKeyID: LTAIPxACpM1voKll
    AccessKeySecret: 85vjeEKlf4bZvlcvHi1XSumy39tfz6
    endpoint: oss-cn-beijing.aliyuncs.com
    sonAccessKeyID: LTAIHgdiUYGPuRsG
    sonAccessKeySecret: 2pgaiHc9TKwcUKwrxt0N2LSy3ZS4qn
    roleArn: acs:ram::1861742825276971:role/aliyunosstokengeneratorrole
swagger2:
  enable: true


