spring:
  #数据库  配置
  datasource:
    druid:
      min-idle: 100
      url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
      max-active: 1000
  #redis 配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # lettuce 和 jedis 的区别:lettuce线程安全，后者反之
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 6
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
  #rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #连接时长
    connection-timeout: 15000
    #开启 confirm 确认机制
    publisher-confirms: true
    #开启 return 确认机制
    publisher-returns: true
#阿里云配置
aliyun:
  oss:
    AccessKeyID: LTAIPxACpM1voKll
    AccessKeySecret: 85vjeEKlf4bZvlcvHi1XSumy39tfz6
    endpoint: oss-cn-beijing.aliyuncs.com
    sonAccessKeyID: LTAIHgdiUYGPuRsG
    sonAccessKeySecret: 2pgaiHc9TKwcUKwrxt0N2LSy3ZS4qn
    roleArn: acs:ram::1861742825276971:role/aliyunosstokengeneratorrole
#可视化接口文档
swagger2:
  enable: true
# 打印sql
logging:
  level:
    com.pan : debug
#微信商户配置
wechat:
  appId: wx16ea5811c16c2db2
  appSecret: 2fb1942ceb55c34dd0d47a3ff4529306
  # 商户号
  mchId: 1516918841
  # 商品描述
  body: test测试1
  # 商户key
  key: Blbbianliba11223344Blbbianliba12
  p12Pass: 1516918841

admin:
  lift:
    status: 0
    lottery: b301b8629b2b2874bff62699f1c8bf45
    joke: 6f6001110b93b2b3ec0acddcf120bb03
    qqResult: b88201743b1ba9d56e0070c7954511eb